schema_version = "1.0.0"

id = "nocturna_theme"
version = "1.2.1"
name = "Nocturna"
tagline = "Nocturna - A Dark Theme for Blender"
maintainer = "DelSQR"
type = "theme"

license = [
  "SPDX:GPL-2.0-or-later",
]

blender_version_min = "5.0.0"


tags = ['Dark']


copyright = [
  "GNU GPL",

]


