# --- Base Configuration ---
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded Config!"

set -g mouse on
set -g base-index 1
set -g renumber-windows on
set -g default-terminal "tmux-256color"
#set-option -g default-shell /usr/bin/nu
set -g history-limit 50000
set -g @continuum-boot 'on'
#set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @continuum-status-on-wrap-style '#[fg=colour2,bg=default]#[fg=colour232,bg=colour2,bold] #{value}min#[fg=colour2,bg=default]'
set -g @continuum-status-off-wrap-style '#[fg=colour8,bg=default]#[fg=colour232,bg=colour8,bold] off#[fg=colour8,bg=default]'

# --- Keybindings ---
bind-key h select-pane -L
bind-key l select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key e set-window-option synchronize-panes

# --- Copy Mode (Vim-style) ---
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# --- Status Bar Appearance ---
set-option -g status-position top
set -g status-interval 1
set -g status-justify absolute-centre

# Transparent background for the bar
set -g status-style fg=default,bg=default

# --- Status Left ---
set -g status-left-length 100
set -g status-left '#[fg=colour6,bold]  #(whoami)  #[fg=colour6,nobold]  #{b:pane_current_path}'

# --- Status Right ---
set -g status-right-length 100
set -g status-right '#[fg=colour3,bold] #{?window_zoomed_flag, ZOOMED ,}#[fg=colour6] #{?SSH_CLIENT, #h ,}#[fg=colour1,bold] #{?client_prefix,  ,}#(~/.config/tmux/scripts/continuum_status_badge.sh) #[fg=colour4,bg=default]#[fg=colour232,bg=colour4,bold]  #S#[fg=colour4,bg=default]'

# --- Window Status (Center) ---

# Inactive Window
set-window-option -g window-status-format ' #[fg=colour6]#I '

# Active Window (Pill shape)
set-window-option -g window-status-current-format '#[fg=colour4, bg=colour232]#[fg=colour232, bg=colour4]  #[fg=colour232,bg=colour4,bold]#W#[fg=colour4, bg=colour232]'

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
